### ISSUE TITLE
Name OSC inputs and outputs like their generator

### ISSUE THREAD

**Issue by simondemeule** [Xmodal/autonomX#136]
Name OSC inputs and outputs like their generator.
See issue #176 

Criteria:

- OSC addresses follow the name of their generator.
- OSC address is in the form of ```/autonomx/[generator_name]/[in, out, in_1, in_2, ...]``` (eg: "/autonomx/SNN_01/in" , "/autonomx/SNN_02/out_3" ...)

Details:

For single address list messages vs multiple adresses atomic messages (See issue #173) :
Messages sending/receiving a list of outputs/inputs are addressed using "out"/"in" . Messages sending/receiving an individual value are addressed using the index of their output/input: "out1","out2","out3","out4","in1","in2","in3,"in4".

**Comment by lucidism** [comment]
to this, I would also add application-wide prefixing for all OSC outputs coming from any generator so that they all share the same "root" address (eg. `/dynamiclight/generator1/out` and `/dynamiclight/spiking-neural-net/out`)
