### ISSUE TITLE
Select a region

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#149]
Part of #146 

**Criteria:**
- Click on a region to select it.
- Change the fill color of the region when it's selected.

**Technical details:**
- When a region is selected, the portion of the neuron matrix **that isn't covered by the area of the selected region** is set to 25% opacity (transition animation not mandatory).
- The borders of similar-type regions (e.g. all other output regions if selected region is output) are set to 70% opacity; all other regions (e.g. all input regions if selected region is output) are set to 25% opacity.
- The selected region has a translucent fill whose opacity value correlates to **the region's momentary input/output value**. The value-opacity mapping ratio is `[0.0, 1.0]` => `[0.0, 0.5]`, so that all cells remain visible even when the region value peaks at 1.

**Comment by aalex** [comment]
@lucidism Please fill this story up with some acceptance criteria. :)

**Comment by lucidism** [comment]
another idea to consider: the initial mockups for the Lattice view featured a small graph in the lower-right corner of the lattice container, which initially represented the mean average of all neuron cells. while we could keep that as reference when no region is selected, this could turn into the active region's graph indicator, with associated colors and such.

![Screenshot_23](https://user-images.githubusercontent.com/34627009/88343708-0416df00-cd10-11ea-9bd2-1f3b594964b2.png)

it could also be interesting to turn the entire corner into a HUD-like reiteration of the active region's I/O parameters, which would prevent the user from having to toggle the rack panel on and back off whenever they want to (the panel collapse feature is also something we've discussed last Monday in the design review, I'm currently prototyping something for this)
