### ISSUE TITLE
Uniformize algorithm grid size settings in the frontend

### ISSUE THREAD

**Issue by simondemeule** [Xmodal/autonomX#152]
We need to update the GUI to reflect changes that will be implemented in #151. The size of the lattice of all generators will be given by a width and height parameter, rather than a single size parameter. We should provide two fields to edit these values.

**Comment by lucidism** [comment]
@simondemeule suggested mockup:
![PARAMS Rack (page 1)](https://user-images.githubusercontent.com/34627009/88721349-541ce980-d0f4-11ea-8645-0de9e88af1f9.png)
we also need to discuss if "Input portion" and "Output portion" are still necessary in light of our new lattice approach. I would assume those are technically parametered on a per-region basis now, so having those as matrix-wide parameters seems a bit, if not entirely useless to me.

**Comment by simondemeule** [comment]
@lucidism Looks great! The input / output portion parameters won’t be necessary once we have input / output regions working, they’re a relic from the SNN code we started from.
