### ISSUE TITLE
Qt 5.12 is no longer supported

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#170]
As users, we want to be able to use the application on Ubuntu GNU/Linux 20.04.

We use one function of QtQuick Renderer that requires a version of Qt that is not supported on Qt 5.12, that we wanted to support.

@simondemeule Can you provide more info about which function requires Qt 5.14, and what value it adds to the software? Can we work around using it?

**Comment by simondemeule** [comment]
@aalex the functions that made me update the Qt version where the `QQuickWindow::beginExternalCommands` and `QQuickWindow::endExternalCommands` functions which just carried over from some of the example code I based my implementation of `GeneratorLatticeRenderer` off (using `QQuickFramebufferObject`). [According to the doc](https://doc.qt.io/qt-5/qquickwindow.html#beginExternalCommands) these aren't even necessary when dealing with OpenGL, and the program runs fine without them. It looks like we can just get rid of them and get back our compatibility.

**Comment by aalex** [comment]
Great!

**Comment by alx-s** [comment]
Cool, so we can support Qt 5.12? means we can support osx 10.12, windows 7 and Ubuntu 16.04 or higher I guess

**Comment by aalex** [comment]
Qt 5.12 is not supported on Ubuntu 16.04, but it is on Ubuntu 20.04. I like to support the latest Ubuntu LTS, but not older than that!
