### ISSUE TITLE
Package for macOS

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#177]
## Criteria
- Provide a app in an archive file for macOS 
- ~~Provide a shell script that automates building an app for macOS.~~

## Technical details:

- Which macOS version?

**Comment by alx-s** [comment]
Qt 5.12 is support for osx 10.12 and later. I guess most users are at least on 10.12 (it is from 2016)

**Comment by alx-s** [comment]
@aalex good to close?

**Comment by aalex** [comment]
> @aalex good to close?

No! The PR hasn't been merged. I'll add in the criteria some info.

**Comment by aalex** [comment]
Packaging is done, but we need an automated script.
