### ISSUE TITLE
Create a "help" rack for SNN generators

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#186]
- Have a rack with a "help" text for the SNN generator.
- The help text should describe what an SNN is, how it works and what are its parameters.
- Provide a short description of the SNN for the "generator" rack.

# Technical details
- Each Generator provides a string. 
- We load a HTML from C++ using the QRC resource system.   
https://stackoverflow.com/questions/63448728/load-text-from-a-file-in-a-qrc-file-in-qml https://doc.qt.io/qt-5/qml-qtquick-text.html
-   Use the Text QML type to display the HTML.  
https://doc.qt.io/qt-5/qml-qtquick-text.html#textFormat-prop

**Comment by lucidism** [comment]
the planned logic behind this has been slightly altered: help text data won't be retrieved as a Generator property, but rather through a globally-exposed `QVariantMap` containing all dynamically-loaded HTML help files, which are then selectively assigned to each generator rack instance according to the value of `type`.

**Comment by aalex** [comment]
@alx-s will provide a new text for the SNN
