### ISSUE TITLE
Manage the generator type in the backend

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#193]
- Change the type of generator
- creation, destruction of generators

**Comment by lucidism** [comment]
this is something we might want to develop in conjunction with #186, considering the current implementation I have for the latter. I was thinking about defining a hash map for generator types which could follow a key-value naming convention such as this one:
```
"snn": "SNN",
"boids": "Boids",
"ca": "Cellular automata"
```
this way, we have a safely-formatted generator type identifier (in this case, the key) we can use internally to target anything from the appropriate parameter rack instance to the help text data, as well as a display name (the value), which can be used in the associated GUI combo box component, in the frontend.

**Comment by alx-s** [comment]
We are opting for remoing the possibility to change the generator type once created. The choice of generator will only happen at creation time.
