### ISSUE TITLE
Choose the new algorithm we want to implement

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#194]
What type of algorithm do we want to implement once we are done with the SNN:
- cellular automata
- boids
- ...

**Comment by aalex** [comment]
I think we should use the Trello board for business analysis for these kinds of decisions - but you can very well decide to move those here.

**Comment by aalex** [comment]
If this is the case, I would probably use a label like "business analysis", or something like "design", or so.

**Comment by alx-s** [comment]
I added a "design" label for business analysis that impact big chunks of dev work. I think it will make it easier for all of us to keep such points in mind on github since we all use it. 
That said, it is not at all about overflowing with "design" issues, just a couple key ones

**Comment by alx-s** [comment]
Decided to create a class/stub/plugin/... system to offload the creation of algorithms on collaborators
