### ISSUE TITLE
Uniformize QtQuick import versions across all component files

### ISSUE THREAD

**Issue by netherwaves** [Xmodal/autonomX#197]
All QtQuick imports, including Layouts, Controls and Window submodules, should be versioned with respect to Qt version 5.12.
An example of this is already implemented in `main.qml`.

## Technical details
These are the import versions we will be using going forward:
```
import QtQuick 2.11
import QtQuick.Controls 2.2
import QtQuick.Layouts 1.3
import QtQuick.Window 2.11
```

**Comment by alx-s** [comment]
@aalex does this justifies a task for the devs to do or a guideline to follow?
