### ISSUE TITLE
Text to explain the SNN

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#213]

**Comment by aalex** [comment]
Spiking Neural Networks (SNNs) are artificial neural networks that mimic the temporal dynamics of natural neural networks.
In addition to neuronal and synaptic state, SNNs incorporate the concept of time into their operating model. The idea is that neurons fire only when a membrane potential—an intrinsic quality of the neuron related to its membrane electrical charge—reaches a specific value. When a neuron fires, it generates a signal that travels to other neurons which, in turn, increase or decrease their potential in accordance with this signal. In SNNs the electrical state of the neurons are modeled by differential equations. Depending on the signals they receive, each neuron is either firing or decaying state.

The Spiking Neurons implemented here are based on the differential equations developed by Mathematicien Eugene M. Izhikevich (Izhikevich 2003). The Izhikevitvh model defines different types of neurons: spiking, resonator and chattering. Each type has a different temporal characteristic.

Here, the neurons have been implemented into a network that contains synaptic plasticity parameters contributing to the network’s ability to evolve and learn over time.

In this Spiking Neural Network implementation, each neuron (each square of the grid) is connected to its neighbors. The electric intensity of the neuron corresponds to the brightness of the square: a bright square corresponds to a firing neuron. As a result, when a neuron fires, some electric potential is sent to the neurons that surround it and patterns emerge and propagate throughout the whole network.

For more information:
Izhikevich E.M. (2003), “Simple Model of Spiking Neurons” in IEEE Transactions on Neural Networks, 14:1569- 1572
https://en.wikipedia.org/wiki/Spiking_neural_network
Parameters:
- General:
  - Width: width (in neurons) of the network
  - Height: heights (in neurons) oh the network
  - Time scale: corresponds to the speed of the network. 
- Neuron Behaviors:
SNN are constituted of excitatory neurons and inhibitory neurons. While excitatory neurons increase the electric potential of other neurons when they fire, the inhibitory neurons decrease the electric potential of other neurons.
  - Inh. Portion: portions of the network corresponding to inhibitory neurons (the rest of the networks consists of excitatory neurons).
  - Inh. Neuron Noise: amount of noise added to the current electrical potential of the neuron.
  - Exc. Neuron Noise: amount of noise added to the current electrical potential of the neuron.
  - Inh. Neuron Type: type of the inhibitory neurons (spiking, chattering, resonator).
  - Exc. Neuron Type: type of the inhibitory neurons (spiking, chattering, resonator).
- Learning: 
  - Stp Strengh: Short-Term synaptic Plasticity, it corresponds to the evolution of the synaptic connection between neurons in relation to the recent activity of the firing neurons.
  - STDP strength: Spike-Timing Dependent Plasticity, it corresponds to the long-term evolution of the synaptic connection between neurons in relation to when they fire: “neurons that fire together connect together.” This corresponds to the ability of the network to develop a long-term memory.
  - Decay constant: corresponds to the speed of the decay of the synaptic connection between neurons after one of the fires

**Comment by alx-s** [comment]
@aalex gonna update the text with simon's corrections.
gonna also check the text's licence and make sure credits are alright

**Comment by aalex** [comment]
Great!
