### ISSUE TITLE
Control the properties of the generators via OSC

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#225]
Acceptance criteria:

- Have each parameters of the generator accessible via OSC
- For each parameter, the OSC address is of the form "/autonomX/[generator_name]/[parameter_name] [value]
- Use the same port for the "input" messages and the "control" messages
- Use a coherent naming system for OSC messages. See spike #226 

Technical details:

- ...
- ...

**Comment by aalex** [comment]
Duplicate of #31
