### ISSUE TITLE
Send and receive OSC via only one port

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#226]
As a user, I prefer to handle only one OSC receiving port in my app, rather than multiple ones, because it's usually easier.

Time-boxed to: 6 days?

## Criteria
- Use the same receiving port for every generator.
- Use the same sending host and port for every generator.
- Addresses are as follow:
  - input: "/[generator_name]/[input_number]" float
  - output: "/[generator_name]/[output_number]" float
  - inputs: "/generator_name]/inputs" float float float float
  - outputs: "/[generator_name]/outputs" float float float float
- Update the OSC.md file in the project's source code.
- Expose the host and ports to the UI so that it can change it dynamically.
- The user should be able to change the sender and host port, and the receiver port in only one place in the software.

## Technical details
- There are actually two lattices for each generator: one inside the thread of the generator, and another one in the thread of the GUI. We might need refactor this so that we have only one thread-safe lattice, instead, or we'll need to investigate it.
- Instead of sending OSC from inside the generator, the facade lattice can send OSC via the global generator.

## Rationale
As of release 0.1 OSC is implemented per generator. This implies each generator must use a unique port. By default all generators start with the same port, this means ports must be changed manually (weird manipulation for people using the software for the first time).

Currently, we cannot use two generators that receive on the same port, because each generator instanciates its own OSC receiver.

For release 0.2 OSC should be implemented globally: only one input port and one output port for the whole application. Messages are then addressed to and from each generator using the name of the generator as described below.

Waiting on #234 the OSC doc and Name of the generators: #231

**Comment by aalex** [comment]
Question: @alx-s What is our new OSC address scheme?

**Comment by aalex** [comment]
Here is an asynchronous queue class: https://github.com/mapmapteam/mapmap/blob/develop/src/control/ConcurrentQueue.h

I think the first step in this spike, now, is to create a single OSC receiver for the whole app, and then we will create more tickets once we have more info.

We cannot have multiple OSC receivers easily listening on the same port, on every operating system, unless we use broadcast or multicast addresses. (but that would be not quite standard and more tricky)
