### ISSUE TITLE
Change the type of the generator

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#229]
As a user I want to be able to change the type (SNN, CA, boid...) of the generator I am using.

Acceptance criteria:

- Have a drop-down menu to select the type of generator
- The parameter interface updates with the parameters associated to the selected generator set to their default value
- The help rack updates with the content associated to the selected generator
- The inputs and outputs zones on the lattice remain the same
- The OSC ports & address for the input and output remain the same
- The OSC addresses for the parameters are changed accordingly to the selected generator

Technical details:

- ...
- ...

**Comment by aalex** [comment]
It seems like this is no longer a good fit in the UX design of the project. Instead, we can delete a generator, and then create a new one.
