### ISSUE TITLE
Have a unique name for each generator at creation time

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#231]
As a user, I want to see the name of each generator, which includes its type and number, so that I know which generator type it's an instance of.

(currently, generators only have a number)

(the UI has a name for the generator)

## Criteria

- Each generator must have a unique name, with no spaces nor special characters.
- Its name is both visible in the user interface and is used in the OSC addressing.
- Change the default name of the generators to `generator type`. See naming details below.

## Naming details
`generator type`: where i is an int that increments starting from 0, and "generator type" corresponds to the type of generator that has been added by the user (SNN, CA...)

## Example 
```
snn_1
snn_2
```

## Technical details
- We could write a unique serial number generator class - each generator type would have an instance of it associated to it.
- We can create a map typeName -> list of names in the factory.
- We don't need to allow renaming in the UI, yet - not until we refactor the OSC interface to have only one sender and one receiver. (then after, we can allow renaming generators in the UI)

## Question
- It seems like we can already rename a generator. Is that working well? Is the unique name already implemented?

## For Later
As of release 0.1 it is possible for users to rename the generators. Even if it would be better to ensure that each names are unique, with no spaces nor special characters (because they are used in the OSC addressing), for now we will leave it to the responsibility of the user not to keep things tidy. We will implement the unicity of generator later

**Comment by aalex** [comment]
All generators are named the same way when initialized. They should be named something like snn_1, instead.

Their name should also be visible in the UI.
