### ISSUE TITLE
save a project

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#238]
As an artist, I want to be able to save a project, so that I can reuse it later.

Depends on #227.

Spike: Time-boxed to 2 days.

## Criteria
- When the user clicks the save button:
- the user can choose a file name and location for the saved project
- we then save the info listed below.
- It must include the type of each generator. (since we plan to 

## Info to save
- the list of generators, including its type
- the parameters of each generators
- the inputs and outputs
- the OSC parameters

## Technical details
- Here is a list of proposed format: (in order of preference)
  - YAML
  - JSON
  - XML
- See: 
  - https://doc.qt.io/qt-5/qtcore-serialization-savegame-example.html
  - https://doc.qt.io/qt-5/datastreamformat.html
  - https://gist.github.com/brcha/d392b2fe5f1e427cc8a6

**Comment by aalex** [comment]
You can look at https://github.com/mapmapteam/mapmap/blob/develop/src/core/ProjectWriter.cpp for inspiration.

We already have a few places in which we iterate through the properties of the generators.

It should probably be done in the C++ side.

**Comment by aalex** [comment]
Let's pop a file save dialog.
