### ISSUE TITLE
Investigate serialization in Qt

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#24]
Options:

- JSON
- XML
- SQLite

**Comment by sofian** [comment]
The appropriate way to deal with serialization in Qt is with QDataStream and QProperties. See https://stackoverflow.com/questions/13835197/serializing-my-custom-class-in-qt

**Comment by sofian** [comment]
Check this out as well: https://stackoverflow.com/questions/1419099/reading-writing-qobjects

**Comment by sofian** [comment]
Problem with QDataStream is that the data will be serialized in binary code, which is not really what we want. Consider instead using JSon or XML eg. look at this: https://github.com/Skycoder42/QtJsonSerializer

**Comment by sofian** [comment]
Check this one out too: https://www.davideling.it/2014/02/qt5-json-serialization/

**Comment by sofian** [comment]
For YAML check this out: https://github.com/simonmeaden/qyaml

**Comment by lucidism** [comment]
here's another resource from the Qt examples, which contextualizes the JSON serialization process in practice: https://doc.qt.io/qt-5.9/qtcore-json-savegame-example.html

**Comment by aalex** [comment]
De-prioritized by the PO.

**Comment by alx-s** [comment]
@aalex This only concerns undo/redo, right? if so, totally deprioritized
