### ISSUE TITLE
Template and documentation to implement a generator in C++

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#242]
As a contributor to the project, I want to have a well-documented template I can start from to write my own generator.

Propose a standardized method for writing new built-in generators in C++.

## Criteria
- Have a generator template to start from
- Document the template and how write a new generator type in C++. 
- See the list of things it should include below.

## Things it should include
The generator type should automatically populate the frontend (parameters panels) and comply with the generator model in the backend (developed in release 0.1 by @simondemeule (backend) and @netherwaves (frontend))

For the frontend, users must be able to specify:
- the generator type
- a short description of the generator
- Its help (longer, in detail, description)
- the name of its parameters, their value ranges, and make them accessible as:
  - linear slider
  - logarithmic slider
  - number box
  - toggle
  - button
  - drop-down list

For the backend, users must be able to:
- code in C++
- have their code run in the lattice/generator model developed in release 0.1 (that is to say their code populates the lattice, they do not have to code anything for the inputs and outputs, nor for the speed that are working by default) 
- have an init function that is called when starting the generator and can be recalled when clicking the re-init button in the interface
- have a main loop that runs the core of their code
- have a generator_main file that centralizes the description of the parameters for the interface (JSAM, YAML...), the init function, and the main loop. 

## Technical details
- Built-in generators will be written in C++ and their code will be inside this git repository.
- The first generator we have in mind is a game of life. 
- Later, we will probably refactor our API to include more dimensions, etc.
- the grid size, grid width, speed, re-init (#184) and reset parameters (#236) must always be present (they are default variables of the generator)

**Comment by aalex** [comment]
Blocked by the implementation of a first second generator. #250

**Comment by netherwaves** [comment]
@aalex @alx-s do we need anything else regarding this issue or is it considered done now?

**Comment by aalex** [comment]
> @aalex @alx-s do we need anything else regarding this issue or is it considered done now?

Good question! I can take a closer look at it in a few days from now - probably on Monday. 

Otherwise, it looks like it's pretty complete.

Let's keep it in the In Review column, and assign it to @alx-s and I!

**Comment by alx-s** [comment]
@aalex @netherwaves 
Julien and I just talked. Julien has the documentation ready for the generator (one last modification he is about to do), the JSON parameters, and he made a generator template. All this looks good!
I propose we close this ticket once Julien does the pull request and we create tickets to enhance the documentation in the future if need be

**Comment by aalex** [comment]
> @aalex @netherwaves 
> Julien and I just talked. Julien has the documentation ready for the generator (one last modification he is about to do), the JSON parameters, and he made a generator template. All this looks good!
> I propose we close this ticket once Julien does the pull request and we create tickets to enhance the documentation in the future if need be 

Ok
