### ISSUE TITLE
Setup an auto-generated documentation system

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#243]
Setup an auto-generated documentation system, so that developers can easily see what classes our code contains.

## Criteria
- Setup an auto-generated documentation system

## Details
- Doxygen could be good.

**Comment by jvlyndark** [comment]
* Pushed update to doxygen branch
* Added the updated Doxygen instructions to contributing
* Added new doxygen file
* bolded instructions inside contributing need to be tested and confirmed
* Old doxygen file needs to be removed once new version is confirmed by @aalex

**Comment by aalex** [comment]
Thank you! I will check it out.
