### ISSUE TITLE
Implement Connway's "game of life" as a new type of generator

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#246]
Implement a new generator type "game of life"

## Criteria
- Implement a new generator type "game of life".
- Expose its attributes, so that the GUI can eventually use it.
- for inputs: if the OSC message is 0, set all the input cells to 0. if the OSC message is !=0, set all the inputs cells to 1. 

## Technical details
- It's 2-dimension.
- The 0 or 1 it can receive are kind of kill switches and spawners.
- https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life
- Can we write a separate executable in the Qt project that is a smoke test? (simply prints 0 and 1 in the console)

## Questions
- Do we have some code that implements it? (Ideally in C++)

**Comment by alx-s** [comment]
Here is an example of implementation taken from Ikegamis's book on ALide : https://github.com/alifelab/alife_book_src/blob/master/chap02/game_of_life.py

**Comment by puneet798** [comment]
Need elaboration on 3rd point in the criteria before merging into dev.

**Comment by alx-s** [comment]
@puneet798 
My idea is the following: GoL cells are binary, either alive (value of 1) or dead (value of 0).
The inputs can serve as means to "kill" or "make alive" cells via OSC messages.
Hence we can imagine that when an input rectangle receives an OSC value of 0 all its cells are instantaneously killed (set to 0). On the other hand, if an input receives an OSC value different from 0 (may it be 1, 234, -0,04...) it turns its corresponding cells alive (set to 1).
Does this make more sense?
