### ISSUE TITLE
Implement Wolfram's cellular automata

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#250]
Implement a new generator type "Wolfram cellular automata". (both the C++ backend object and the GUI)

## Criteria
- Implement a new generator type "wolfram cellular automata".
- Expose its parameters, so that the GUI can eventually use it.
- for inputs: if the OSC message is 0, set all the input cells to 0. if the OSC message is !=0, set all the inputs cells to 1. 
- The Wolfram cellular automata runs indefinitely. The lattice displays the queue. (?)
- The parameters to be exposed are :
  - number of the rule (we put them all 0 - 255)
  - seed (either "one living cell in the center of the first line" or "the first line is random")

## Technical details
- see #273 for the GUI
- It's 1-dimension.
- The 0 or 1 it can receive are kind of kill switches and spawners.
- https://mathworld.wolfram.com/ElementaryCellularAutomaton.html
- You can write a unit test that checks if the new generator type can generate numbers like it should. (see #268)

**Comment by alx-s** [comment]
Here is an exemple of implementation taken from Ikegami's book on artificial life : https://github.com/alifelab/alife_book_src/blob/master/chap02/cellular_automata_1d.py
