### ISSUE TITLE
Integrate the dynamical list of generator types

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#251]
Dynamically populate the list of generator types.

## Critera
- Dynamically populate the list of generator types.
- Integrate the code done for #260 the type registry spike.

## Technical details
- create a type registry in C++ (with a template method in a global class) ? - Like this: https://github.com/aalex/tempi/blob/master/tempi/nodefactory.h#L53 or using https://doc.qt.io/qt-5/qmetatype.html
- generate a listmodel
- QML can read that to offer the options

**Comment by jvlyndark** [comment]
I think this and several other tickets are all closely related and can either be collapsed into fewer tickets and/or would benefit from us focusing on them at the same time. They all have to do with the dynamic creation / binding / exposing of generators from a list, allowing users to run different generators simultaneously, etc.

Examples:
[Issue 274](https://github.com/Xmodal/autonomX/issues/274)
[Issue 247](https://github.com/Xmodal/autonomX/issues/247)
[Issue 231](https://github.com/Xmodal/autonomX/issues/231)
[Issue 251](https://github.com/Xmodal/autonomX/issues/251)
[Issue 260](https://github.com/Xmodal/autonomX/issues/260)

**Comment by aalex** [comment]
Question: Do we do a switch/case statement to dynamically create the right type of generator? Yes, something simple like that can be done, but we could create a map of generator types instead, perhaps. (or you can just do a switch/case)

**Comment by aalex** [comment]
Making sure the names are unique can simply be a method in an existing class.
