### ISSUE TITLE
Allow to have cellular automata generators in the UI

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#254]
Allow to have cellular automata generators in the UI.

Depends on #250 #246

## Criteria
- Provide the two generators listed below in the UI.

## Technical details
- We can keep the hard-coding of the list of generators we can instantiate, at this point.

## List of generators to add
- Conway game of life
- Wolframe cellular automata

**Comment by alx-s** [comment]
@aalex Was this issue actually tackled in the current sprint ? can we consider it done or should we keep it?

**Comment by aalex** [comment]
@alx-s Can you try out the app, do some QA testing and tell us? I am not exactly sure of what the current state of the dev branch is. Has all the work-in-progress branches been merged? Can this be considered done?
