### ISSUE TITLE
(spike) Dynamically expose properties depending on the generator type

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#274]
## Criteria
- Allow the UI to list properties (name and type) a generator has

## Technical Details
- You can look in MapMap
- There is MetaObject

**Comment by jvlyndark** [comment]
This and several other tickets are tightly coupled and/or share a lot of similar tasks needed steps for completing. Maybe we can reorganize them in the next meeting?
See [Issue 251](https://github.com/Xmodal/autonomX/issues/251) for other examples.
