### ISSUE TITLE
Adding Rules to Game of Life Algorithm 

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#302]
## Criteria

Add commonly known patterns to game of life algorithm. 

## Technical Details

- Add a drop down menu depicting the common known patterns in GOL e.g space ship, beehive etc. (https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life)
- The user should be able to switch between different patterns on the lattice.
- Integrate it with the GUI.

**Comment by puneet798** [comment]
I closed this by myself by mistake. Opening it for review.

**Comment by aalex** [comment]
This issue has been mentioned in a PR that is closed. Can we close this issue, now?

**Comment by puneet798** [comment]
yes!
