### ISSUE TITLE
Game of Life Bug - No change in the lattice dimensions at the backend

### ISSUE THREAD

**Issue by puneet798** [Xmodal/autonomX#305]
## latticeWidth and latticeHeight not updated in the backend 

If lattice size is changed in GOL GUI (once someone has chosen a pattern, say a glider) - it does not get updated in the backend but does change in the GUI.

For example, choosing a pattern such as glider - it is supposed to start at latticeWidth/2 and latticeHeight/2. It does when both lattice width and height have default value as 20 However on changing the dimension of the lattice the glider initial position stays at the same coordinate (20,20).

**Comment by aalex** [comment]
Can we close this ticket? Was this a bug?

**Comment by puneet798** [comment]
Yes. Now it is done.
