### ISSUE TITLE
Make Global OSC Parameters in GUI

### ISSUE THREAD

**Issue by jvlyndark** [Xmodal/autonomX#307]
OSC parameters (host, address, port) for both OSC Send and Receive are now global, shared by all generators.

These settings, which are currently implemented individually on a per-generator basis, need to be turned into a single, global instance to control all generators simultaneously.

### Criteria

- Use same GUI layout as is currently implemented for individual generators, but in global section
- Remove OSC parameters from individual generators' json files

**Comment by aalex** [comment]
This is already mentioned in #291.

**Comment by jvlyndark** [comment]
> This is already mentioned in #291.

ah darn, you're right. my bad!
