### ISSUE TITLE
Control the parameters of the generator via OSC

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#31]
Depends on #226 

## Acceptance criteria
- Have each parameters of the generator accessible via OSC
- For each parameter, the OSC address is of the form "/[generator_name]/[parameter_name] [value]
- Use the same port for the "input" messages and the "control" messages
- Use a consistent naming system for OSC messages. See spike #226 ❓ 

## Technical details
- See in MapMap. On a du code pour automatiser le contrôle de properties avec des adresses OSC.
- It might trigger the entire recalculation of the lattice for a generator
- It might trigger a big refactor of the main loop of the generators.
- Maybe we should take into account the resizing of the lattice only at the beginning of each iteration.
- We might route the handling of the parameter changes at different times in the process.

**Comment by sofian** [comment]
Check this code from MapMap in which OSC messages are parsed so as to automatically update properties:
https://github.com/mapmapteam/mapmap/blob/develop/src/control/OscInterface.cpp

In particular look at lines 216 and 245 where properties are directly set using a function call setElementProperty().

**Comment by aalex** [comment]
@jvlyndark Would like to review the code that will be done about this.

**Comment by aalex** [comment]
Where can we find the list of parameters to control?

Do we also want to be able to reset the generators, reset the regions?
