### ISSUE TITLE
Make Wolfram CA scroll from bottom to top

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#312]
As a user, I want to see the Wolfram CA scroll from bottom to top so that its outputs have a constantly varying signal.

## Acceptance criteria
- Have the different generations of the CA scroll from bottom to top

## Technical details
- Each line must be computed accordingly to the one above so that the CA scrolls from bottom to top and inputs can be computed too (#313 )

**Comment by aalex** [comment]
![PXL_20210630_154056600.jpg](https://user-images.githubusercontent.com/293677/123991184-7f5d2800-d998-11eb-8c66-c17d1eabbe55.jpg)

**Comment by aalex** [comment]
@alx-s will do a BA meeting with @puneet798
