### ISSUE TITLE
Wolfram CA input mechanics

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#313]
As a user, I want to send inputs to the Wolfram CA so that I can infuence its evolution

## Acceptance criteria
- Inputs must write to the generator/lattice only when an osc input message is received
- Round the numbers:
  - if the input message is  approximately zero (0):  set the selected input cells to 0
  - if the input message is not approximately zero (0) : set the selected input cells to 1

## Technical details
- The sequencing of the computation is important: first compute a line (n) according to the line above (n-1) (normal bottom to top scrolling), then write the input value on the line (n). Then compute the next ine (n-1) according to the one above (n-2) and set the input values of line (n-1), etc... 
- Each generator must handle incoming OSC in its specific way. We might need to add an abstract method for that.

**Comment by aalex** [comment]
@alx-s will do a BA meeting with @puneet798
