### ISSUE TITLE
modify the input behavior of the wolfram CA

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#346]
## rational
As of now, if the input message is >0.1 the program writes "1" in the CA, and if the input message is <0.1 it writes "0" in the CA. This is problematic with the current OSC input implementation that does not allows for messages to individual inputs but only to all of them at the same time.  As a consequence, if users wants to send "1" to one of the inputs they have to send a value to the other inputs too...\

## Fix
- When an input message is received:
- - if the value of an input is ">0.1" write "1" on the CA
- - else, do not do anything (do not write a value, just leave the current input cells as they are)

**Comment by aalex** [comment]
Let's document that the input regions for this generator are best when used on the last - most recent - row.
