### ISSUE TITLE
remove the "/input" at the beginning of all OSC output message

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#357]
Current output messages are in the form ```/input /SpinkingNet_01/output f f f f```
Instead, they should be: ```/SpinkingNet_01/output f f f f```

**Comment by alx-s** [comment]
@jvlyndark I believe this is not relevent to the current state of the OSC and must be an older bug you fixed since. can we close?

**Comment by aalex** [comment]
![image](https://user-images.githubusercontent.com/293677/133475269-2636737e-28d2-40c8-93ca-24988ba94607.png)

**Comment by aalex** [comment]
Is this bug still occurring? Answer: yes.

**Comment by aalex** [comment]
Refactoring this might require the OSC sender to be access the generator that sends the OSC message. (?)

Question: Can't we simply add an argument to a new method of the OSC sender?

**Comment by aalex** [comment]
We might fix this bug later, but we'll probably need to make sure we still have a backward-compatible OSC Interface, and keep the existing legacy OSC message signature within the same major version.
