### ISSUE TITLE
Run a SNN generator

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#5]
As an artist, I want to be able to run a Spiking Neuron Network (SNN) so that it generates numbers that I can use in an artwork.

**Acceptance criteria**
* Give and see the name of my generator - the default name is “generator0”
* View the type of my generator - that is “Spiking Neural Network”
* Actually run a SNN in the software.
* Internally, the parameter values of the SNN are (no need to show them in the GUI):
- - number of neurons (400)
- - network type (grid)
- - inhibitory neuron type (chattering)
- - excitatory neuron type (chattering)
- - inhibitory portion (20%)
- - input portion (20%)
- - output portion (20%)
- - stp (off)
- - stdp (on)
- - output time window size (10)

**Wireframe**
![Storyboard](https://user-images.githubusercontent.com/3448675/82940506-effa6f80-9f62-11ea-9a85-f10dd9af24be.jpg)

**Technical details**
We already have a source code for the SNN. Alex S uses it extensively and can help demo/explain it.

**Comment by aalex** [comment]
Questions: What size should it be? How many cells.

**Comment by alx-s** [comment]
We will start with a 400 neuron SNN. I will specify here the different parameters

**Comment by aalex** [comment]
So, it's 20 by 20?

**Comment by aalex** [comment]
Question: At this point, the properties are read-only? We will be able to modify in the next story #6 ?
