### ISSUE TITLE
Draw inputs and outputs on the generator's representation

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#61]
As an artist I want to "draw" on the generator so that I can easily create inputs and outputs on my generator.

Acceptance criteria:

- I have 4 inputs and 4 outputs
- For each input and output :
  - I can drag a rectangular region on the lattice by click and dragging the mouse
  - I can move a region by click and dragging with the mouse
  - I can move a corner of a region by click and dragging with the mouse (the draggable square is 6 pixels)
  - I can drag a border of the region (either vertical or horizontal)
  - I can see the current value as a vu-meter
  - I can see the evolution over the past 10 seconds as a graph
  - There is a distinctive, though coherent, visual aspect (cells selected, vu-meter, graph)
  - each inputs and outputs are linked with the OSC messages

- For each input:
  - the corresponding OSC value is added to the selected cells' current values
- For each output:
  - the corresponding OSC value is the mean of the selected cells' values

Mockup:

<img width="1397" alt="newmockup" src="https://user-images.githubusercontent.com/293677/88336862-b6947500-cd03-11ea-8409-cb5b4a07e27a.png">

Technical details:

- Draw the regions in QML Canvas (JavaScript)

**Comment by aalex** [comment]
@lucidism Can you populate with a wireframe/mockup or more criteria? :)

**Comment by aalex** [comment]
We can draw ellipses later.

**Comment by lucidism** [comment]
@aalex @alx-s here is an updated mockup for the Lattice view input/output management. some concepts are still up to further debate (notably how we route data into an input node from various possible sources through the field with the small chain link icon and whether or not we allow for certain nodes to be disabled).

![Lattice view](https://user-images.githubusercontent.com/34627009/87883861-5be3dc00-c9d8-11ea-9f3b-2c28ee9d16a7.png)

also, here's a suggested UX roadmap for the neuron matrix view (left side of the aforementioned mockup):
- the visible area can be zoomed (middle mouse/touchpad scroll) and panned (right-click drag);
- the visible area can be manually zoomed with the number field in the lower-left corner of the container;
- the visible area can be reset (centered in view; 100% zoom value) by using the `Shift+C` shortcut;
- upon arriving from the Generator view, no zone is selected;
- zones can be selected by left-clicking on them;
- zones can be created by left-click dragging an unselected area of the matrix;
- zones can be moved by left-click dragging a pre-existing zone;
- zones can be deleted by selecting and hitting the `Del` key;
- zone-drawing type (input / output) can be toggled through the 2 buttons in the upper-left corner of the container or by hitting the `T` key;
- the currently selected zone features a small caret to the left of the concerned track, in the I/O configuration panel (right side of screen).

some further functionality ideas for the future:
- the matrix container could be resized by left-click dragging the window separation down to 33% and up to 66% of its original value (precise ratios TBD);
- the I/O configuration panel could be collapsed to the right to make room for precise zone drawing (and vice-versa).

**Comment by alx-s** [comment]
@lucidism  Following our discussion and taking into account the different points we raised, what would think of something in this vein? (please excuse the crude and barbaric collage ;) )
Maybe taking this kind of approach is an interesting middle ground between the vertical racks we discussed and the horizontal ones you designed so that we have a constant view of 1/ the list of generators, 2/ the lattice view/drawing of the selected generator, 3/ the different parameters in collapsable racks

<img width="1397" alt="generator_view_1" src="https://user-images.githubusercontent.com/3448675/88011816-4ceb4f80-cae6-11ea-8e3a-571f0b8a2e22.png">

**Comment by simondemeule** [comment]
@lucidism I think something like this would work. Maybe having the option to collapse the generators list or lattice could be helpful for smaller screens.

If adopt the Connection View (#133) paradigm however there really isn't a use for input / output racks, since all settings are already exposed in that view. 

If we want to be consistent with it, we could make the Default View's lattice middle section behave like a single-generator version of the Connection View — this just means enabling the user to create / delete / edit inputs and outputs, and adding in a bottom bar that allows editing the same parameters exposed in the Connection View's bottom bar (sampling settings, time smoothing, history visualizer).

**Comment by aalex** [comment]
Nice to ideas:

- Shift keeps the proportions.
- Alt keeps the pivot point at the center.
- Alt drag duplicates.

**Comment by simondemeule** [comment]
[LearnOpenGL](https://learnopengl.com/Advanced-OpenGL/Anti-Aliasing) tutorial related to antialiasing for zooming on the matrix

**Comment by simondemeule** [comment]
Here is what we discussed for adding inputs and outputs, for a future task:
- there are two "+" buttons, one for adding inputs, one for adding outputs 
 - clicking the button allows you to drag a zone over the lattice to create an input
 - the user has visual feedback indicating they are in input or output creation mode
 - pressing escape exits this mode
- inputs and outputs can still be created quickly with mouse / keyboard combinations:
 - double click adds an input zone
 - double click + shift adds an output zone
 - the user has visual feedback indicating they are in input or output creation mode
 - pressing escape exits this mode
