### ISSUE TITLE
View the current value of the generator output node

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#7]
As an artist, I want to see at a glance the current value of the output node of my SNN generator as an indicator light rather than as a number I have to read.

**Acceptance criteria**

- View the current single value of the output node of my generator as a color that changes between 0 and 100% brightness, or something similar.

**Wireframe**

<img width="449" alt="Screen Shot 2020-05-26 at 15 21 34" src="https://user-images.githubusercontent.com/3448675/82941605-a14dd500-9f64-11ea-8f05-8ba0fbe6eedb.png">

**Technical details**

**Comment by aalex** [comment]
Perhaps do the average of a square region of a generator, and do a slide. (jit.slide) of it.

**Comment by aalex** [comment]
On peut créer des "offset" pour la fenêtre d'observation dans le modèle - mais dans ce qui nous intéresse à court terme, on veut observer le modèle au complet.

**Comment by aalex** [comment]
Le générateur va fournir un signal ou une propriété unique qui est un float. Le GUI va observer ce chiffre et changer son apparence en fonction de cela.

**Comment by aalex** [comment]
It's been implemented.
