### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#99]
Rename the project.

Rename:

- The Qt project name(s)
- This repository.
- the domain name for our custom types and config, if any.
- The documentation.

To AutonomX

**Comment by aalex** [comment]
@question for @alx-s : what name should we rename it to?

**Comment by alx-s** [comment]
@aalex waiting : waiting to have sofian back and a few days of sleeping on it and the name will be decided soon ;)

**Comment by aalex** [comment]
Yes! Indeed! This is a question for later.

**Comment by sofian** [comment]
My suggestion: AutonomX
Combines Xmodal + autonomy
also X is one letter away from Y in the alphabet.

**Comment by aalex** [comment]
#159 is a duplicate
